/*
 * generated by Xtext 2.12.0
 */
package org.softlang.qegal.lang


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class QegalStandaloneSetup extends QegalStandaloneSetupGenerated {

	def static void doSetup() {
		new QegalStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
