/*
 * generated by Xtext 2.12.0
 */
package org.softlang.qegal.lang.validation

import org.eclipse.xtext.validation.Check
import org.softlang.qegal.lang.qegal.QegalPackage
import org.softlang.qegal.lang.qegal.Variable
import org.eclipse.xtext.EcoreUtil2
import org.softlang.qegal.lang.qegal.Rule
import org.softlang.qegal.lang.qegal.Term
import com.google.common.base.Strings
import java.util.Objects

/**
 * This class contains custom validation rules. 
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class QegalValidator extends AbstractQegalValidator {

	public static val INVALID_NAME = 'undefined'

	@Check
	def checkGreetingStartsWithCapital(Variable variable) {
		val term = EcoreUtil2.getContainerOfType(variable, Term)
		val rule = EcoreUtil2.getContainerOfType(term, Rule)

		// If head contains this variable it must be defined in body.
		val head = if(rule.direction == "<-") rule.left else rule.right
		val body = if(rule.direction == "->") rule.left else rule.right

		if (head.contains(term)) {
			for (b : body)
				for (v : EcoreUtil2.getAllContentsOfType(b, Variable))
					if (Objects.equals(v.name, variable.name))
						return;

			// Variable is not defined in the body.
			if (!Character.isUpperCase(variable.name.charAt(0))) {
				error('Variables is not defined in the body', QegalPackage.Literals.VARIABLE__NAME, INVALID_NAME)
			}
		}
	}

}
